<?php
require_once('./config/connection.php');
require_once('./model/utente/object.class.php');
require_once('./model/utente/provider.class.php');
require_once('./model/indirizzo/object.class.php');
require_once('./model/indirizzo/provider.class.php');
require_once('./model/gioco/object.class.php');
require_once('./model/gioco/provider.class.php');
require_once('./model/sett/object.class.php');
require_once('./model/sett/provider.class.php');
require_once('./model/carrello/object.class.php');
require_once('./model/carrello/provider.class.php');
require_once('./model/carta/object.class.php');
require_once('./model/carta/provider.class.php');
require_once('./model/inserzione/object.class.php');
require_once('./model/inserzione/provider.class.php');
?>