<?php
require_once('./config/connection.php');
require_once('./model/utente/object.class.php');
require_once('./model/utente/provider.class.php');
require_once('./model/indirizzo/object.class.php');
require_once('./model/indirizzo/provider.class.php');
require_once('./model/gioco/object.class.php');
require_once('./model/gioco/provider.class.php');
?>